### ISSUE TITLE
Is it possible to use this in platform Linux?

### ISSUE THREAD

**Issue by longfenghou** [hcmlab/vadnet#2]
Hello, i would like to know if it is possible to use this application in platform Linux by simply changing the cmd files?
Another question is that "Does the CPU works for the Online VAD?"
Thanks for your time,

**Comment by frankenjoe** [comment]
If you want to use SSI as backend, you will have to use [mobileSSI](https://github.com/hcmlab/mobileSSI). The VAD model itself is Python only.

**Comment by giorgionanfa** [comment]
Hi, this project is very interesting! I was trying to run it on Linux (i also tried for Windows and it works fine). Which steps should i follow to run the project on Linux?
Thanks in advance
