### ISSUE TITLE
No module named 'encodings'

### ISSUE THREAD

**Issue by kli017** [hcmlab/vadnet#24]
hello after runing the do_cmd I got the following error:
Current thread 0x000119dc (most recent call first):
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
any suggestion?

**Comment by mrg79433283** [comment]
> hello after runing the do_cmd I got the following error: Current thread 0x000119dc (most recent call first): Fatal Python error: initfsencoding: unable to load the file system codec ModuleNotFoundError: No module named 'encodings' any suggestion?

you should check the file: python36._pth

**Comment by DidaDidaDidaD** [comment]
我也遇到了这个问题，什么情况？ python36._pth这里是空的，还有解压后的python36文件夹里是有encodings文件夹的，bug啊
